### ISSUE TITLE
Uninitialized Variables default to null

### ISSUE THREAD

**Issue by mpmenne** [vdmpeniel/MetroLinkGuide#1]
Hey this is pretty minor, but will go a long way when people are evaluating your code.

Uninitialized variables always default to null, so there's no need to set them to null.   Just leave them as unitialized. 

(This is one of those Java ideosyncracies that you have to learn on the Java certification exam.)

![screen shot 2016-09-13 at 9 00 18 pm](https://cloud.githubusercontent.com/assets/217904/18497628/7c535920-79f5-11e6-85ca-8408b9dcf413.png)

**Comment by vdmpeniel** [comment]
Thank you very much I didn't know Java sets variables to null by default! I really appreciate any correction! :D 

```
El Martes 13 de septiembre de 2016 22:04, Mike Menne <notifications@github.com> escribió:
```

 Hey this is pretty minor, but will go a long way when people are evaluating your code.Uninitialized variables always default to null, so there's no need to set them to null. Just leave them as unitialized. (This is one of those Java ideosyncracies that you have to learn on the Java certification exam.)—
