### ISSUE TITLE
No self reference needed for private variables

### ISSUE THREAD

**Issue by mpmenne** [vdmpeniel/MetroLinkGuide#2]
This is another minor thing that will help when people are evaluating your code.

First be sure that all variables always start with a lower case (Lower CamelCase) per the [Java coding conventions](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case).

Next, anytime a instance variable is private, you can access that variable without specify the owning class.  For example, `JAD.dataBaseAccess.getStations();` can be just `dataBaseAccess.getStations();`

**Comment by vdmpeniel** [comment]
Mike if I try to use the private property dataBaseAccess without the owning class (it was JAD I am changing it for a lowercase name) I get an error Error:(28, 34) java: non-static variable dataBaseAccess cannot be referenced from a static contextAny way around that? Thank you! 

```
El Martes 13 de septiembre de 2016 22:42, Mike Menne <notifications@github.com> escribió:
```

 This is another minor thing that will help when people are evaluating your code.First be sure that all variables always start with a lower case (Lower CamelCase) per the Java coding conventions.Next, anytime a instance variable is private, you can access that variable without specify the owning class. For example, JAD.dataBaseAccess.getStations(); can be just dataBaseAccess.getStations();—

**Comment by vdmpeniel** [comment]
Ok, This is what I did: static DataBaseAccess dataBaseAccess;
static UserInterface userInterface;
static Timer timer;In that way  I can use private properties inside main without the owning class. thanks!

**Comment by mpmenne** [comment]
sounds good!
