### ISSUE TITLE
Nice UI

### ISSUE THREAD

**Issue by mpmenne** [vdmpeniel/MetroLinkGuide#4]
It's not often that I get to compliment the UI of a command line tool!

I really like what you did there with the UI.  Breaking the UI logic out into a separate class keeps things clean and the brackets are really cool.

![screen shot 2016-09-13 at 9 45 02 pm](https://cloud.githubusercontent.com/assets/217904/18498361/7bf78b6c-79fb-11e6-8e95-40a83dde8e39.png)

**Comment by vdmpeniel** [comment]
Thank you for the compliment! I appreciate it. I try to do my best no matter how trivial the work at hand may seem. Thank you very much for your time! 

```
El Martes 13 de septiembre de 2016 22:46, Mike Menne <notifications@github.com> escribió:
```

 It's not often that I get to compliment the UI of a command line tool!I really like what you did there with the UI. Breaking the UI logic out into a separate class keeps things clean and the brackets are really cool.—
